#   A basic travis.yml boilerplate for Django projects
#
#   The set-up assumes a postgreSQL database.
#
#   Replace the following variables in the code:
# * your_project_settings
# * your_github_username
# * your_repo

language: python

python:
  - 2.7
  - 3.5

services: sqlite3

env:
  - DJANGO=1.10.0

before_install:
  - export DJANGO_SETTINGS_MODULE=demo.settings
  - export PYTHONPATH=$HOME/builds/hainnt/DemoDjango
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet

script:
  - python manage.py syncdb --noinput
