#   A basic travis.yml boilerplate for Django projects
#
#   The set-up assumes a postgreSQL database.
#
#   Replace the following variables in the code:
# * your_project_settings
# * your_github_username
# * your_repo

language: python

python:
  - "3.5"

sudo: required

notifications:
  email: false
  slack: 'englishtool:4bB96RvsqKdgxqo59chj1KTh#travis-ci-notify'
    on_success: always
    on_failure: always

env:
  - DJANGO=1.10

before_install:
  - export DJANGO_SETTINGS_MODULE=demo.settings
  - export PYTHONPATH=$HOME/builds/hainnt/DemoDjango
  - export PIP_USE_MIRRORS=true

install:
  - pip install django==$DJANGO --quiet

script: nosetests
